version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: hoshidori-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hoshidori
      POSTGRES_USER: hoshidori
      POSTGRES_PASSWORD: hoshidori
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: